import = ["/Users/satoshi/.config/alacritty/themes/dark_pastels.toml"]

[env]
LC_CTYPE = "ja_JP.UTF-8"
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "HackGen35 Console NF"
style = "Bold"

[font.bold_italic]
family = "HackGen35 Console NF"
style = "Bold"

[font.italic]
family = "HackGen35 Console NF"
style = "Bold"

[font.normal]
family = "HackGen35 Console NF"
style = "Regular"

[font.offset]
y = 1

[scrolling]
history = 100000
multiplier = 2

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 4
y = 4
