[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {'colorscheme': 'iceberg'}
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
  autocmd VimEnter * nested colorscheme iceberg
'''
